version: '3.8'

services:
  app:
    build: .
    image: zanovix-ai-website
    container_name: zanovix-ai-website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development